# Generated by Django 3.1.6 on 2021-02-05 06:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='tokens',
        ),
        migrations.AddField(
            model_name='document',
            name='tokens',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
