# Generated by Django 3.1.6 on 2021-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210205_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tokens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
