# Generated by Django 3.1.6 on 2021-02-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='wordcloud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
