version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: planesdb
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=unrecano@recano.club
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8081:80"
    depends_on:
      - db
  web:
    build:
      context: ../planes
      dockerfile: ../docker/dev
    volumes:
      - ../planes:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_POST=5432
      - DATABASE_NAME=planesdb
      - DATABASE_USER=postgres
      - DATABASE_PASS=secret
      - SECRET_KEY=abcdefghijklmnopq
    depends_on:
      - db
