version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: planesdb
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=unrecano@recano.club
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8081:80"
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: ../planes
      dockerfile: ../docker/web/dev
    volumes:
      - ../planes:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
