version: '3'
volumes:
  app_data:
services:
  web:
    restart: always
    build:
      context: ../planes
      dockerfile: ../docker/web/prod
    volumes:
      - app_data:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_POST=5432
      - DATABASE_NAME=planesdb
      - DATABASE_USER=postgres
      - DATABASE_PASS=secret
      - SECRET_KEY=abcdefghijklmnopq
  nginx:
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - app_data:/data
    ports:
      - "4083:80"
      - "4433:443"
    depends_on:
      - web