version: '3'
volumes:
  app_data:
services:
  web:
    restart: always
    build:
      context: ../planes
      dockerfile: ../docker/web/prod
    volumes:
      - app_data:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  nginx:
    restart: always
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - app_data:/code
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web