version: '3'
services:
  web:
    restart: always
    build:
      context: ../planes
      dockerfile: ../docker/prod
    volumes:
      - ../planes:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_POST=5432
      - DATABASE_NAME=planesdb
      - DATABASE_USER=postgres
      - DATABASE_PASS=secret
      - SECRET_KEY=abcdefghijklmnopq
